# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:48:49+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, constr


class CaseType(Enum):
    LowerCase = 'LowerCase'
    UpperCase = 'UpperCase'
    SentenceCase = 'SentenceCase'
    TitleCase = 'TitleCase'


class IdType(Enum):
    VAT = 'VAT'
    SSN = 'SSN'


class LoremType(Enum):
    normal = 'normal'
    business = 'business'


class NameType(Enum):
    firstname = 'firstname'
    surname = 'surname'
    fullname = 'fullname'


class NumberValidation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    country: constr(min_length=1, max_length=2)
    number: constr(min_length=1, max_length=100)


class TextActionType(Enum):
    Transform = 'Transform'
    Replace = 'Replace'


class TextDto(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Optional[str] = None


class TextType(Enum):
    paragraphs = 'paragraphs'
    words = 'words'
